project:
  type: book

book:
  title: "Introduction to Data Science"
  subtitle: "DSST289"
  author: "Erik Fredner"
  date: today
  chapters:
    - index.qmd
    - notes01.qmd
    - notes02.qmd
    - notes03.qmd
    - notes04.qmd
    - notes05.qmd
    - notes06.qmd
    - notes07.qmd
    - notes08.qmd
    - notes09.qmd
    - notes10.qmd

bibliography: references.bib

format:
  html:
    anchor-sections: true
    code-tools: true
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    number-sections: true
    smooth-scroll: true
    toc: true

